BUBBLE_C = bubblesort.c
MERGE_C = mergesort.c
BUBBLE_PY = bubble.py
MERGE_PY = merge.py

bubble_comp:
	gcc -o bubble ${BUBBLE_C}
merge_comp:
	gcc -o merge ${MERGE_C}
all:
	make bubble_comp merge_comp
clean:
	rm -f *.obj *.o 


	